version: '3'

services:
  frontend:
    image: "sskorol/aqa-fe:0.0.4"
    ports:
      - "8262:8262"
    networks:
      - automation
  selenoid:
    networks:
      - automation
    image: aerokube/selenoid:latest
    volumes:
      - "${PWD}:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${PWD}/video:/opt/selenoid/video"
      - "${PWD}/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=${PWD}/video/
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "selenoid_automation" ]
    ports:
      - "4444:4444"
  selenoid-ui:
    image: "aerokube/selenoid-ui:latest"
    depends_on:
      - selenoid
    ports:
      - "8081:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
    networks:
      - automation

networks:
  automation:
    driver: bridge
